### ISSUE TITLE
Infografia Ana

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Anamichel-leon#2]
[INFOGRAFIA FASES DE GESTION DE PROYECTOS DE SOFTWARE -ANA LEON.pdf](https://github.com/user-attachments/files/16753100/INFOGRAFIA.FASES.DE.GESTION.DE.PROYECTOS.DE.SOFTWARE.-ANA.LEON.pdf)

**Comment by Irvingzr16** [comment]
Redacción y ortografía: 16.67%
Exposición de ideas centrales:16.67%
Organización de la información: 16.67%
Uso de imagines y colores: 16.67%
Presentación visual: 16.67%
Referencias y presentación: 16.67%

porcentaje final:100%


**Calificación final: 20/20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
